# Generated by Django 5.0.7 on 2024-07-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("participants", models.IntegerField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("result", models.CharField(max_length=50)),
            ],
        ),
    ]
