# Generated by Django 5.0.7 on 2024-07-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="period_end",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="business",
            name="period_start",
            field=models.CharField(max_length=50),
        ),
    ]
