# Generated by Django 5.0.7 on 2024-07-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0003_performance_remove_business_participants_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="businesstype",
            field=models.CharField(default="None", max_length=10, verbose_name="신규"),
        ),
    ]
