# Generated by Django 5.0.7 on 2024-07-19 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0004_business_businesstype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business",
            old_name="businesstype",
            new_name="business_type",
        ),
    ]
