# Generated by Django 5.0.7 on 2024-07-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0005_rename_businesstype_business_business_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="budget",
            field=models.FloatField(default=0.0, verbose_name="사업금액"),
        ),
    ]
